import tkinter as tk

janela = tk.Tk()
janela.geometry('1000x500+0+0')
janela.title('SUPER AÇAI')

Frame_Top = tk.Frame()
Frame_Top.place(relx= 0,rely=0.003,relwidth=1, relheight=1)
Frame_Top.configure(relief='groove')
Frame_Top.configure(borderwidth = '8')
Frame_Top.configure(relief="groove")
Frame_Top.configure(background="#6d32a8")

label_nome = tk.Label()
label_nome.place(relx= 0.005,rely=0.01,relwidth=1, relheight=0.08)
label_nome.configure(background="#d9d9d9")
label_nome.configure(disabledforeground="black")
label_nome.configure(font='-family{segoe UI}- size 150')
label_nome.configure(foreground='black')
label_nome.configure(relief= 'raised')
label_nome.configure(borderwidth = '4')
label_nome.configure(relief="raised")
label_nome.configure(text="SUPER AÇAI")


Frame_left = tk.Frame(Frame_Top)
Frame_left.place(relx= 0,rely=0.08,relwidth=0.354, relheight=0.645)
Frame_left.configure(relief= 'raised')
Frame_left.configure(borderwidth = '8')
Frame_left.configure(relief="raised")
Frame_left.configure(background="white")

Frame_mid = tk.Frame(Frame_Top)
Frame_mid.place(relx= 0.347,rely=0.08,relwidth=0.354, relheight=0.645)
Frame_mid.configure(relief= 'raised')
Frame_mid.configure(borderwidth = '8')
Frame_mid.configure(relief="raised")
Frame_mid.configure(background="white")

Frame_bottom = tk.Frame(Frame_Top)
Frame_bottom.place(relx= 0,rely=0.72,relwidth=0.7, relheight=0.28)
Frame_bottom.configure(relief= 'raised')
Frame_bottom.configure(borderwidth = '8')
Frame_bottom.configure(relief="raised")
Frame_bottom.configure(background="#e0a4ed")

Frame_right = tk.Frame(Frame_Top)
Frame_right.place(relx= 0.697,rely=0.080,relwidth=0.31, relheight=0.38)
Frame_right.configure(relief= 'raised')
Frame_right.configure(borderwidth = '8')
Frame_right.configure(relief="raised")
Frame_right.configure(background="white")

Frame_bot_right = tk.Frame(Frame_Top)
Frame_bot_right.place(relx= 0.697,rely=0.43,relwidth=0.31, relheight=0.5)
Frame_right.configure(relief= 'raised')
Frame_bot_right.configure(borderwidth = '8')
Frame_bot_right.configure(relief="raised")
Frame_bot_right.configure(background="white")

#criando listbox
acai_listbox = tk.Listbox(Frame_bottom)
acai_listbox.place(relx= 0.3,rely=0.05,relwidth=0.2, relheight=0.2)
acai_listbox.configure(background="#d9d9d9")
acai_listbox.configure(disabledforeground="grey")
acai_listbox.configure(font='-family{arial}-size 14')
acai_listbox.configure(foreground='black')
acai_listbox.configure(highlightbackground="black")
acai_listbox.configure(highlightcolor= "black")
acai_listbox.configure(borderwidth = '5')
acai_listbox.configure(justify="right")

adicionais = tk.Listbox(Frame_bottom)
adicionais.place(relx= 0.3,rely=0.29,relwidth=0.2, relheight=0.2)
adicionais.configure(background="#d9d9d9")
adicionais.configure(disabledforeground="grey")
adicionais.configure(font='-family{arial}-size 14')
adicionais.configure(foreground='black')
adicionais.configure(highlightbackground="black")
adicionais.configure(highlightcolor= "black")
adicionais.configure(borderwidth = '5')
adicionais.configure(justify="right")

valores = tk.Listbox(Frame_bottom)
valores.place(relx= 0.3,rely=0.54,relwidth=0.2, relheight=0.2)
valores.configure(background="#d9d9d9")
valores.configure(disabledforeground="black")
valores.configure(font='-family{arial}-size 14')
valores.configure(foreground='black')
valores.configure(highlightbackground="black")
valores.configure(highlightcolor= "black")
valores.configure(borderwidth = '5')
valores.configure(justify="right")

dinheiro_entry = tk.Entry(Frame_bottom)
dinheiro_entry.place(relx= 0.3,rely=0.78,relwidth=0.2, relheight=0.2)
dinheiro_entry.configure(background="#d9d9d9")
dinheiro_entry.configure(disabledforeground="black")
dinheiro_entry.configure(font='-family{arial}-size 14')
dinheiro_entry.configure(foreground='black')
dinheiro_entry.configure(highlightbackground="black")
dinheiro_entry.configure(highlightcolor= "black")
dinheiro_entry.configure(borderwidth = '5')
dinheiro_entry.configure(justify="left")

total = tk.Listbox(Frame_bottom)
total.place(relx= 0.75,rely=0.05,relwidth=0.2, relheight=0.2)
total.configure(background="#d9d9d9")
total.configure(disabledforeground="black")
total.configure(font='-family{arial}-size 14')
total.configure(foreground='black')
total.configure(highlightbackground="black")
total.configure(highlightcolor= "black")
total.configure(borderwidth = '5')
total.configure(justify="right")

troco = tk.Listbox(Frame_bottom)
troco.place(relx=0.75,rely=0.54,relwidth=0.2, relheight=0.2)
troco.configure(background="#d9d9d9")
troco.configure(disabledforeground="black")
troco.configure(font='-family{arial}-size 14')
troco.configure(foreground='black')
troco.configure(highlightbackground="black")
troco.configure(highlightcolor= "black")
troco.configure(borderwidth = '5')
troco.configure(justify="right")

listbox = tk.Listbox(Frame_bot_right)
listbox.place(relx= 0,rely=0,relwidth=1, relheight=1)
listbox.configure(background="#f7f7cb")
listbox.configure(disabledforeground="black")
listbox.configure(font='-family{arial}-size 10')
listbox.configure(foreground='black')
listbox.configure(highlightbackground="black")
listbox.configure(highlightcolor= "black")
listbox.configure(borderwidth = '5')

calculadora_entry = tk.Entry(Frame_right)
calculadora_entry.place(relx= 0.02,rely=0.01,relwidth=71, relheight=45, bordermode='ignore')
calculadora_entry.configure(background="#d9d9d9")
calculadora_entry.configure(disabledforeground="black")
calculadora_entry.configure(font='-family{arial}-size 14')
calculadora_entry.configure(foreground='black')
calculadora_entry.configure(highlightbackground="black")
calculadora_entry.configure(highlightcolor= "black")
calculadora_entry.configure(borderwidth = '5')
calculadora_entry.configure(justify="right")

#CRIANDO OS TIPOS DE AÇAI

acai_300ml_entry = tk.Entry(Frame_left)
acai_300ml_entry.place(relx= 0.7,rely=0.1,relwidth=0.2, relheight=35, bordermode='ignore')
acai_300ml_entry.configure(background="#d9d9d9")
acai_300ml_entry.configure(disabledforeground="black")
acai_300ml_entry.configure(font='-family{arial}-size 14')
acai_300ml_entry.configure(foreground='black')
acai_300ml_entry.configure(highlightbackground="black")
acai_300ml_entry.configure(highlightcolor= "black")
acai_300ml_entry.configure(borderwidth = '5')

acai_500ml_entry = tk.Entry(Frame_left)
acai_500ml_entry.place(relx= 0.7,rely=0.15,relwidth=0.2, relheight=35, bordermode='ignore')
acai_500ml_entry.configure(background="#d9d9d9")
acai_500ml_entry.configure(disabledforeground="black")
acai_500ml_entry.configure(font='-family{arial}-size 14')
acai_500ml_entry.configure(foreground='black')
acai_500ml_entry.configure(highlightbackground="black")
acai_500ml_entry.configure(highlightcolor= "black")
acai_500ml_entry.configure(borderwidth = '5')

acai_700ml_entry = tk.Entry(Frame_left)
acai_700ml_entry.place(relx= 0.7,rely=0.20,relwidth=0.2, relheight=0.35, bordermode='ignore')
acai_700ml_entry.configure(background="#d9d9d9")
acai_700ml_entry.configure(disabledforeground="black")
acai_700ml_entry.configure(font='-family{arial}-size 14')
acai_700ml_entry.configure(foreground='black')
acai_700ml_entry.configure(highlightbackground="black")
acai_700ml_entry.configure(highlightcolor= "black")
acai_700ml_entry.configure(borderwidth = '5')

#CRIANDO OS ADICIONAIS#

leite_entry = tk.Entry(Frame_mid)
leite_entry.place(relx= 0.7,rely=0.1,relwidth=0.2, relheight=0.35, bordermode='ignore')
leite_entry.configure(background="#d9d9d9")
leite_entry.configure(disabledforeground="black")
leite_entry.configure(font='-family{arial}-size 14')
leite_entry.configure(foreground='black')
leite_entry.configure(highlightbackground="black")
leite_entry.configure(highlightcolor= "black")
leite_entry.configure(borderwidth = '5')

leite_cond_entry = tk.Entry(Frame_mid)
leite_cond_entry.place(relx= 0.7,rely=0.2,relwidth=0.2, relheight=0.35, bordermode='ignore')
leite_cond_entry.configure(background="#d9d9d9")
leite_cond_entry.configure(disabledforeground="black")
leite_cond_entry.configure(font='-family{arial}-size 14')
leite_cond_entry.configure(foreground='black')
leite_cond_entry.configure(highlightbackground="black")
leite_cond_entry.configure(highlightcolor= "black")
leite_cond_entry.configure(borderwidth = '5')

pacoca_entry = tk.Entry(Frame_mid)
pacoca_entry.place(relx= 0.7,rely=0.3,relwidth=0.2, relheight=0.35, bordermode='ignore')
pacoca_entry.configure(background="#d9d9d9")
pacoca_entry.configure(disabledforeground="black")
pacoca_entry.configure(font='-family{arial}-size 14')
pacoca_entry.configure(foreground='black')
pacoca_entry.configure(highlightbackground="black")
pacoca_entry.configure(highlightcolor= "black")
pacoca_entry.configure(borderwidth = '5')

morango_entry = tk.Entry(Frame_mid)
morango_entry.place(relx= 0.7,rely=0.4,relwidth=0.2, relheight=0.35, bordermode='ignore')
morango_entry.configure(background="#d9d9d9")
morango_entry.configure(disabledforeground="black")
morango_entry.configure(font='-family{arial}-size 14')
morango_entry.configure(foreground='black')
morango_entry.configure(highlightbackground="black")
morango_entry.configure(highlightcolor= "black")
morango_entry.configure(borderwidth = '5')

banana_entry = tk.Entry(Frame_mid)
banana_entry.place(relx= 0.7,rely=0.5,relwidth=0.2, relheight=0.35, bordermode='ignore')
banana_entry.configure(background="#d9d9d9")
banana_entry.configure(disabledforeground="black")
banana_entry.configure(font='-family{arial}-size 14')
banana_entry.configure(foreground='black')
banana_entry.configure(highlightbackground="black")
banana_entry.configure(highlightcolor= "black")
banana_entry.configure(borderwidth = '5')

granola_entry = tk.Entry(Frame_mid)
granola_entry.place(relx= 0.7,rely=0.6,relwidth=0.2, relheight=0.35, bordermode='ignore')
granola_entry.configure(background="#d9d9d9")
granola_entry.configure(disabledforeground="black")
granola_entry.configure(font='-family{arial}-size 14')
granola_entry.configure(foreground='black')
granola_entry.configure(highlightbackground="black")
granola_entry.configure(highlightcolor= "black")
granola_entry.configure(borderwidth = '5')

nutela_entry = tk.Entry(Frame_mid)
nutela_entry .place(relx= 0.7,rely=0.7,relwidth=0.2, relheight=0.35, bordermode='ignore')
nutela_entry .configure(background="#d9d9d9")
nutela_entry .configure(disabledforeground="black")
nutela_entry .configure(font='-family{arial}-size 14')
nutela_entry .configure(foreground='black')
nutela_entry .configure(highlightbackground="black")
nutela_entry .configure(highlightcolor= "black")
nutela_entry .configure(borderwidth = '5')

#CRIANDO OS BOTÕES

botao_total = tk.Button()
botao_total.place(relx= 0.699,rely=0.92,width=100, height=45)
botao_total.configure(activeforeground='#ececec')
botao_total.configure(activebackground='black')
botao_total.configure(background="#d9d9d9")
botao_total.configure(borderwidth = '5')
botao_total.configure(disabledforeground="grey")
botao_total.configure(font='-family{segoe UI}-size 14')
botao_total.configure(foreground='black')
botao_total.configure(highlightbackground="grey")
botao_total.configure(highlightcolor= "black")
botao_total.configure(pady='0')
botao_total.configure(text='TOTAL')

botao_recibo = tk.Button()
botao_recibo.place(relx= 0.773,rely=0.92,width=100, height=45)
botao_recibo.configure(activeforeground='#ececec')
botao_recibo.configure(activebackground='black')
botao_recibo.configure(background="#d9d9d9")
botao_recibo.configure(borderwidth = '5')
botao_recibo.configure(disabledforeground="grey")
botao_recibo.configure(font='-family{segoe UI}-size 14')
botao_recibo.configure(foreground='black')
botao_recibo.configure(highlightbackground="grey")
botao_recibo.configure(highlightcolor= "black")
botao_recibo.configure(pady='0')
botao_recibo.configure(text='RECIBO')

botao_limpar = tk.Button()
botao_limpar.place(relx= 0.848,rely=0.92,width=100, height=45)
botao_limpar.configure(activeforeground='#ececec')
botao_limpar.configure(activebackground='black')
botao_limpar.configure(background="#d9d9d9")
botao_limpar.configure(borderwidth = '5')
botao_limpar.configure(disabledforeground="grey")
botao_limpar.configure(font='-family{segoe UI}-size 14')
botao_limpar.configure(foreground='black')
botao_limpar.configure(highlightbackground="grey")
botao_limpar.configure(highlightcolor= "black")
botao_limpar.configure(pady='0')
botao_limpar.configure(text='LIMPAR')

botao_sair = tk.Button()
botao_sair .place(relx= 0.848,rely=0.92,width=100, height=45)
botao_sair.configure(activeforeground='#ececec')
botao_sair.configure(activebackground='black')
botao_sair.configure(background="#d9d9d9")
botao_sair.configure(borderwidth = '5')
botao_sair.configure(disabledforeground="grey")
botao_sair.configure(font='-family{segoe UI}-size 14')
botao_sair.configure(highlightbackground="grey")
botao_sair.configure(highlightcolor= "black")
botao_sair.configure(pady='0')
botao_sair.configure(text='SAIR')

####
custo_acai = tk.Label(Frame_bottom)
custo_acai.place(relx=0.01, rely=0.1, height= 25, width=200, bordermode='ignore')
custo_acai.configure(background='#e394d2')
custo_acai.configure(disabledforeground ='#a3a3a3')
custo_acai.configure(font='-family{segoe UI}-size 14')
custo_acai.configure(foreground='black')
custo_acai.configure(text='Custo do Açai')

dinheiro = tk.Label(Frame_bottom)
dinheiro.place(relx=0.01, rely=0.82, height=25, width=200, bordermode='ignore')
dinheiro.configure(background='#e394d2')
dinheiro.configure(disabledforeground='grey')
dinheiro.configure(font='-family{segoe UI}-size 14')
dinheiro.configure(foreground='black')
dinheiro.configure(text='Dinheiro')

sub_total= tk.Label(Frame_bottom)
sub_total.place(relx=0.5, rely=0.35, height=25, width=200, bordermode='ignore')
sub_total.configure(background='#e394d2')
sub_total.configure(disabledforeground='grey')
sub_total.configure(font='-family{segoe UI}-size 14')
sub_total.configure(foreground='black')
sub_total.configure(text='Sub Total')

total= tk.Label(Frame_bottom)
total.place(relx=0.5, rely=0.6, height=25, width=200, bordermode='ignore')
total.configure(background='#e394d2')
total.configure(disabledforeground='grey')
total.configure(font='-family{segoe UI}-size 14')
total.configure(foreground='black')
total.configure(text='Custo Total')

troco = tk.Label(Frame_bottom)
troco.place(relx=0.5, rely=0.6, height=25, width=200, bordermode='ignore')
troco.configure(background='#e394d2')
troco.configure(disabledforeground='grey')
troco.configure(font='-family{segoe UI}-size 14')
troco.configure(foreground='black')
troco.configure(text='Troco')

#######
label_acai = tk.Label(Frame_left)
label_acai.place(relx=0.004, rely=0.100, height=0.08, width=130)
label_acai.configure(background='#e394d2')
label_acai.configure(borderwidth='4')
label_acai.configure(disabledforeground='grey')
label_acai.configure(font='-family{arial black}- size 25 -weight bold')
label_acai.configure(foreground='black')
label_acai.configure(text='Açais')

label_adicionais = tk.Label(Frame_mid)
label_adicionais.place(relx=0, rely=0.0, height=0.08, width=130)
label_adicionais.configure(background='#e394d2')
label_adicionais.configure(borderwidth='4')
label_adicionais.configure(disabledforeground='grey')
label_adicionais.configure(font='-family{arial black}-size 25 -weight bold')
label_adicionais.configure(foreground='black')
label_adicionais.configure(text='Adicionais')

#check button acai
botao_acai300ml = tk.Checkbutton(Frame_left)
botao_acai300ml.configure(text= 'Açai 300ml')
#botao_acai300ml.configure(varaible=var1)
botao_acai300ml.place(relx=0.1, rely=0.1, height=35, bordermode= 'ignore')
botao_acai300ml.configure(font='-family {arial} -size 14')
botao_acai300ml.configure(background='grey')
#botao_acai300ml.configure(command=m.acai300ml)

botao_acai500ml = tk.Checkbutton(Frame_left)
botao_acai500ml.configure(text= 'Açai 500ml ')
#botao_acai500ml.configure(varaible=var2)
botao_acai500ml.place(relx=0.1, rely=0.2, height=35, bordermode= 'ignore')
botao_acai500ml.configure(font='-family {arial} -size 14')
botao_acai500ml.configure(background='grey')
#botao_acai500ml.configure(command=m.acai500ml)

botao_acai700ml = tk.Checkbutton(Frame_left)
botao_acai700ml.configure(text= 'Açai 700ml')
#botao_acai700ml.configure(varaible=var3)
botao_acai700ml.place(relx=0.1, rely=0.3, height=35, bordermode= 'ignore')
botao_acai700ml.configure(font='-family {arial} -size 14')
botao_acai700ml.configure(background='grey')
#botao_acai700ml.configure(command=m.acai700ml)

#check button adicionais
botao_leite = tk.Checkbutton(Frame_mid)
botao_leite.configure(text= 'Leite ')
#botao_leite.configure(varaible=var4)
botao_leite.place(relx=0.1, rely=0.45, height=35, bordermode= 'ignore')
botao_leite.configure(font='-family {arial} -size 10')
botao_leite.configure(background='grey')
#botao_leite.configure(command=m.leite)


botao_leite_cond = tk.Checkbutton(Frame_mid)
botao_leite_cond.configure(text= 'Leite condensado ')
#botao_leite_cond.configure(varaible=var5)
botao_leite_cond.place(relx=0.1, rely=0.55, height=35, bordermode= 'ignore')
botao_leite_cond.configure(font='-family {arial} -size 10')
botao_leite_cond.configure(background='grey')
#botao_leite.configure(command=m.leite_cond)

botao_morango = tk.Checkbutton(Frame_mid)
botao_morango.configure(text= 'Morango')
#botao_morango.configure(varaible=var6)
botao_morango.place(relx=0.1, rely=0.65, height=35, bordermode= 'ignore')
botao_morango.configure(font='-family {arial} -size 10')
botao_morango.configure(background='grey')
#botao_morango.configure(command=m.morango)

botao_banana = tk.Checkbutton(Frame_mid)
botao_banana.configure(text= 'Banana')
#botao_banana.configure(varaible=var6)
botao_banana.place(relx=0.1, rely=0.75, height=35, bordermode= 'ignore')
botao_banana.configure(font='-family {arial} -size 10')
botao_banana.configure(background='grey')
#botao_banana.configure(command=m.banana)

botao_granola = tk.Checkbutton(Frame_mid)
botao_granola.configure(text= 'Granola')
#botao_granola.configure(varaible=var7)
botao_granola.place(relx=0.1, rely=0.85, height=35, bordermode= 'ignore')
botao_granola.configure(font='-family {arial} -size 10')
botao_granola.configure(background='grey')
#botao_granola.configure(command=m.granola)

botao_nutela = tk.Checkbutton(Frame_mid)
botao_nutela.configure(text= 'Nutela ')
#botao_nutela.configure(varaible=var8)
botao_nutela.place(relx=0.1, rely=0.95, height=35, bordermode= 'ignore')
botao_nutela.configure(font='-family {arial} -size 10')
botao_nutela.configure(background='grey')
#botao_nutela.configure(command=m.nutela)







janela.mainloop()








janela.mainloop()
